version: '3'
services:
  realtime:
    image: supabase/realtime:0.7.1
    ports:
      - "4000:4000"
    environment:
      DB_HOST: db
      DB_NAME: postgres
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_PORT: 5432
      PORT: 4000
      HOSTNAME: localhost
      JWT_SECRET: SOMETHING_SUPER_SECRET
      SECURE_CHANNELS: 'true'
    depends_on:
      - db
  db:
    image: supabase/postgres
    ports:
      - "5432:5432"
    volumes:
    - ./dev/postgres/mnt:/docker-entrypoint-initdb.d/
    command:
    - postgres
    - -c
    - wal_level=logical
    environment: 
      POSTGRES_PASSWORD: postgres