[
  {server, [
    {certfile, "certs/server.crt"},
    {keyfile, "certs/server.key"},
    {secure_renegotiate, true}
  ]},
  {client, [
    {cacertfile, "certs/ca.crt"},
    {verify, verify_none},
    {secure_renegotiate, true}
  ]}
].
