# What Postgres reports for the policies of test/support/sql_logex_policies.ex and for the functions
# they call. Generated by test/realtime/tenants/sql_logex_fixtures_test.exs, do not edit by hand.
#
# To regenerate, run this against a Postgres of this major version (POSTGRES_IMAGE selects it):
#
#   SQL_LOGEX_WRITE_FIXTURES=1 mix test test/realtime/tenants/sql_logex_fixtures_test.exs
#
%{
  database: %{
    collate: "en_US.UTF-8",
    ctype: "en_US.UTF-8",
    locale_provider: "c"
  },
  functions: [
    %{
      config: nil,
      language: "sql",
      name: "jwt",
      return_type: "jsonb",
      schema: "auth",
      security_definer: false,
      source:
        "\n      select coalesce(\n               nullif(current_setting('request.jwt.claim', true), ''),\n               nullif(current_setting('request.jwt.claims', true), '')\n             )::jsonb\n    ",
      volatility: "s"
    },
    %{
      config: nil,
      language: "sql",
      name: "role",
      return_type: "text",
      schema: "auth",
      security_definer: false,
      source: "\n  select nullif(current_setting('request.jwt.claim.role', true), '')::text;\n",
      volatility: "s"
    },
    %{
      config: nil,
      language: "sql",
      name: "uid",
      return_type: "uuid",
      schema: "auth",
      security_definer: false,
      source: "\n  select nullif(current_setting('request.jwt.claim.sub', true), '')::uuid;\n",
      volatility: "s"
    },
    %{
      config: nil,
      language: "sql",
      name: "topic",
      return_type: "text",
      schema: "realtime",
      security_definer: false,
      source: "\nselect nullif(current_setting('realtime.topic', true), '')::text;\n",
      volatility: "s"
    }
  ],
  policies: [
    %{
      cmd: "a",
      name: "generator_authenticated_all_topic_insert",
      permissive: true,
      qual: nil,
      roles: ["authenticated"],
      with_check: "true"
    },
    %{
      cmd: "r",
      name: "generator_authenticated_all_topic_read",
      permissive: true,
      qual: "true",
      roles: ["authenticated"],
      with_check: nil
    },
    %{
      cmd: "r",
      name: "generator_authenticated_read_broadcast",
      permissive: true,
      qual: "((realtime.topic() = 'fixture_topic'::text) AND (extension = 'broadcast'::text))",
      roles: ["authenticated"],
      with_check: nil
    },
    %{
      cmd: "r",
      name: "generator_authenticated_read_broadcast_and_presence",
      permissive: true,
      qual:
        "((realtime.topic() = 'fixture_topic'::text) AND (extension = ANY (ARRAY['presence'::text, 'broadcast'::text])))",
      roles: ["authenticated"],
      with_check: nil
    },
    %{
      cmd: "r",
      name: "generator_authenticated_read_broadcast_based_on_claim",
      permissive: true,
      qual:
        "((realtime.topic() = 'fixture_topic'::text) AND (extension = 'broadcast'::text) AND COALESCE((((current_setting('request.jwt.claims'::text, true))::jsonb ->> 'broadcast_read'::text))::boolean, false))",
      roles: ["authenticated"],
      with_check: nil
    },
    %{
      cmd: "r",
      name: "generator_authenticated_read_matching_user_sub",
      permissive: true,
      qual: "((( SELECT auth.uid() AS uid))::text = 'c0ffee00-1111-4222-8333-444455556666'::text)",
      roles: ["authenticated"],
      with_check: nil
    },
    %{
      cmd: "r",
      name: "generator_authenticated_read_presence",
      permissive: true,
      qual: "((realtime.topic() = 'fixture_topic'::text) AND (extension = 'presence'::text))",
      roles: ["authenticated"],
      with_check: nil
    },
    %{
      cmd: "r",
      name: "generator_authenticated_read_presence_based_on_claim",
      permissive: true,
      qual:
        "((realtime.topic() = 'fixture_topic'::text) AND (extension = 'presence'::text) AND COALESCE((((current_setting('request.jwt.claims'::text, true))::jsonb ->> 'presence_read'::text))::boolean, false))",
      roles: ["authenticated"],
      with_check: nil
    },
    %{
      cmd: "r",
      name: "generator_authenticated_read_presence_for_sub",
      permissive: true,
      qual:
        "((realtime.topic() = 'fixture_topic'::text) AND (extension = 'presence'::text) AND ((( SELECT auth.uid() AS uid))::text = 'c0ffee00-1111-4222-8333-444455556666'::text))",
      roles: ["authenticated"],
      with_check: nil
    },
    %{
      cmd: "a",
      name: "generator_authenticated_write_broadcast",
      permissive: true,
      qual: nil,
      roles: ["authenticated"],
      with_check: "((realtime.topic() = 'fixture_topic'::text) AND (extension = 'broadcast'::text))"
    },
    %{
      cmd: "a",
      name: "generator_authenticated_write_broadcast_and_presence",
      permissive: true,
      qual: nil,
      roles: ["authenticated"],
      with_check:
        "((realtime.topic() = 'fixture_topic'::text) AND (extension = ANY (ARRAY['presence'::text, 'broadcast'::text])))"
    },
    %{
      cmd: "a",
      name: "generator_authenticated_write_matching_user_sub",
      permissive: true,
      qual: nil,
      roles: ["authenticated"],
      with_check: "((( SELECT auth.uid() AS uid))::text = 'c0ffee00-1111-4222-8333-444455556666'::text)"
    },
    %{
      cmd: "a",
      name: "generator_authenticated_write_persistence",
      permissive: true,
      qual: nil,
      roles: ["authenticated"],
      with_check: "((realtime.topic() = 'fixture_topic'::text) AND (extension = 'persistence'::text))"
    },
    %{
      cmd: "a",
      name: "generator_authenticated_write_presence",
      permissive: true,
      qual: nil,
      roles: ["authenticated"],
      with_check: "((realtime.topic() = 'fixture_topic'::text) AND (extension = 'presence'::text))"
    },
    %{
      cmd: "r",
      name: "generator_broken_read_presence",
      permissive: true,
      qual: "( SELECT public.test_log_error() AS test_log_error)",
      roles: ["authenticated"],
      with_check: nil
    },
    %{
      cmd: "a",
      name: "generator_broken_write_presence",
      permissive: true,
      qual: nil,
      roles: ["authenticated"],
      with_check: "( SELECT public.test_log_error() AS test_log_error)"
    },
    %{
      cmd: "r",
      name: "generator_read_matching_user_role",
      permissive: true,
      qual: "(( SELECT auth.role() AS role) = 'authenticated'::text)",
      roles: ["public"],
      with_check: nil
    },
    %{
      cmd: "r",
      name: "generator_slow_read",
      permissive: false,
      qual: "( SELECT true\n   FROM pg_sleep((1)::double precision) pg_sleep(pg_sleep))",
      roles: ["authenticated"],
      with_check: nil
    },
    %{
      cmd: "a",
      name: "generator_slow_write",
      permissive: false,
      qual: nil,
      roles: ["authenticated"],
      with_check: "( SELECT true\n   FROM pg_sleep((1)::double precision) pg_sleep(pg_sleep))"
    },
    %{
      cmd: "a",
      name: "generator_write_matching_user_role",
      permissive: true,
      qual: nil,
      roles: ["public"],
      with_check: "(( SELECT auth.role() AS role) = 'authenticated'::text)"
    },
    %{
      cmd: "*",
      name: "grammar_all_using_only",
      permissive: true,
      qual: "(realtime.topic() = 'x'::text)",
      roles: ["authenticated"],
      with_check: nil
    },
    %{
      cmd: "r",
      name: "grammar_and_in_or",
      permissive: true,
      qual: "((realtime.topic() = 'a'::text) OR ((realtime.topic() = 'b'::text) AND (extension = 'broadcast'::text)))",
      roles: ["authenticated"],
      with_check: nil
    },
    %{
      cmd: "r",
      name: "grammar_and_three",
      permissive: true,
      qual: "((realtime.topic() = 'a'::text) AND (extension = 'broadcast'::text) AND (private = true))",
      roles: ["authenticated"],
      with_check: nil
    },
    %{
      cmd: "r",
      name: "grammar_auth_role",
      permissive: true,
      qual: "(auth.role() = 'authenticated'::text)",
      roles: ["authenticated"],
      with_check: nil
    },
    %{
      cmd: "r",
      name: "grammar_case_searched",
      permissive: true,
      qual: "\nCASE\n    WHEN (extension = 'broadcast'::text) THEN true\n    ELSE false\nEND",
      roles: ["authenticated"],
      with_check: nil
    },
    %{
      cmd: "r",
      name: "grammar_case_simple",
      permissive: true,
      qual: "\nCASE extension\n    WHEN 'broadcast'::text THEN true\n    ELSE false\nEND",
      roles: ["authenticated"],
      with_check: nil
    },
    %{
      cmd: "r",
      name: "grammar_claims_boolean",
      permissive: true,
      qual: "(((current_setting('request.jwt.claims'::text, true))::jsonb ->> 'k'::text))::boolean",
      roles: ["authenticated"],
      with_check: nil
    },
    %{
      cmd: "r",
      name: "grammar_claims_text",
      permissive: true,
      qual: "(((current_setting('request.jwt.claims'::text, true))::jsonb ->> 'k'::text) = 'v'::text)",
      roles: ["authenticated"],
      with_check: nil
    },
    %{
      cmd: "r",
      name: "grammar_coalesce",
      permissive: true,
      qual: "(COALESCE(realtime.topic(), 'x'::text) = 'x'::text)",
      roles: ["authenticated"],
      with_check: nil
    },
    %{
      cmd: "r",
      name: "grammar_concat_null",
      permissive: true,
      qual: "(realtime.topic() = ('x'::text || NULL::text))",
      roles: ["authenticated"],
      with_check: nil
    },
    %{
      cmd: "r",
      name: "grammar_doubled_quote",
      permissive: true,
      qual: "(realtime.topic() = 'it''s'::text)",
      roles: ["authenticated"],
      with_check: nil
    },
    %{
      cmd: "r",
      name: "grammar_eq_null",
      permissive: true,
      qual: "(realtime.topic() = NULL::text)",
      roles: ["authenticated"],
      with_check: nil
    },
    %{
      cmd: "r",
      name: "grammar_event",
      permissive: true,
      qual: "(event = 'x'::text)",
      roles: ["authenticated"],
      with_check: nil
    },
    %{
      cmd: "r",
      name: "grammar_exists",
      permissive: true,
      qual: "(EXISTS ( SELECT 1\n   FROM realtime.messages m2\n  WHERE (m2.topic = realtime.topic())))",
      roles: ["authenticated"],
      with_check: nil
    },
    %{
      cmd: "r",
      name: "grammar_false",
      permissive: true,
      qual: "false",
      roles: ["authenticated"],
      with_check: nil
    },
    %{
      cmd: "r",
      name: "grammar_in_single",
      permissive: true,
      qual: "(extension = 'broadcast'::text)",
      roles: ["authenticated"],
      with_check: nil
    },
    %{
      cmd: "r",
      name: "grammar_is_not_null",
      permissive: true,
      qual: "(realtime.topic() IS NOT NULL)",
      roles: ["authenticated"],
      with_check: nil
    },
    %{
      cmd: "r",
      name: "grammar_is_null",
      permissive: true,
      qual: "(realtime.topic() IS NULL)",
      roles: ["authenticated"],
      with_check: nil
    },
    %{
      cmd: "r",
      name: "grammar_jwt_text",
      permissive: true,
      qual: "((auth.jwt() ->> 'k'::text) = 'v'::text)",
      roles: ["authenticated"],
      with_check: nil
    },
    %{
      cmd: "r",
      name: "grammar_jwt_text_initplan",
      permissive: true,
      qual: "(( SELECT (auth.jwt() ->> 'k'::text)) = 'v'::text)",
      roles: ["authenticated"],
      with_check: nil
    },
    %{
      cmd: "r",
      name: "grammar_neq",
      permissive: true,
      qual: "(realtime.topic() <> 'x'::text)",
      roles: ["authenticated"],
      with_check: nil
    },
    %{
      cmd: "r",
      name: "grammar_not",
      permissive: true,
      qual: "(NOT (realtime.topic() = 'x'::text))",
      roles: ["authenticated"],
      with_check: nil
    },
    %{
      cmd: "r",
      name: "grammar_not_in",
      permissive: true,
      qual: "(extension <> ALL (ARRAY['broadcast'::text, 'presence'::text]))",
      roles: ["authenticated"],
      with_check: nil
    },
    %{
      cmd: "r",
      name: "grammar_not_in_single",
      permissive: true,
      qual: "(extension <> 'broadcast'::text)",
      roles: ["authenticated"],
      with_check: nil
    },
    %{
      cmd: "r",
      name: "grammar_nullif",
      permissive: true,
      qual: "(NULLIF(realtime.topic(), 'x'::text) = 'y'::text)",
      roles: ["authenticated"],
      with_check: nil
    },
    %{
      cmd: "r",
      name: "grammar_or_in_and",
      permissive: true,
      qual: "(((realtime.topic() = 'a'::text) OR (realtime.topic() = 'b'::text)) AND (extension = 'broadcast'::text))",
      roles: ["authenticated"],
      with_check: nil
    },
    %{
      cmd: "r",
      name: "grammar_private",
      permissive: true,
      qual: "(private = true)",
      roles: ["authenticated"],
      with_check: nil
    },
    %{
      cmd: "r",
      name: "grammar_regex_case_sensitive",
      permissive: true,
      qual: "(realtime.topic() ~ 'public:lobby'::text)",
      roles: ["authenticated"],
      with_check: nil
    },
    %{
      cmd: "r",
      name: "grammar_restrictive",
      permissive: false,
      qual: "(realtime.topic() = 'x'::text)",
      roles: ["authenticated"],
      with_check: nil
    },
    %{
      cmd: "r",
      name: "grammar_to_anon_authenticated",
      permissive: true,
      qual: "(realtime.topic() = 'x'::text)",
      roles: ["anon", "authenticated"],
      with_check: nil
    },
    %{
      cmd: "r",
      name: "grammar_to_public",
      permissive: true,
      qual: "(realtime.topic() = 'x'::text)",
      roles: ["public"],
      with_check: nil
    },
    %{
      cmd: "r",
      name: "grammar_true",
      permissive: true,
      qual: "true",
      roles: ["authenticated"],
      with_check: nil
    },
    %{
      cmd: "r",
      name: "lobby",
      permissive: true,
      qual: "(realtime.topic() ~* 'public:lobby'::text)",
      roles: ["authenticated"],
      with_check: nil
    },
    %{
      cmd: "r",
      name: "users receive on own channel",
      permissive: true,
      qual:
        "((realtime.topic() = ('user:'::text || auth.uid())) AND (extension = ANY (ARRAY['broadcast'::text, 'presence'::text])))",
      roles: ["authenticated"],
      with_check: nil
    },
    %{
      cmd: "r",
      name: "users receive on own channel (initplan)",
      permissive: true,
      qual:
        "((realtime.topic() = ('user:'::text || ( SELECT auth.uid() AS uid))) AND (extension = ANY (ARRAY['broadcast'::text, 'presence'::text])))",
      roles: ["authenticated"],
      with_check: nil
    },
    %{
      cmd: "a",
      name: "users send on own channel",
      permissive: true,
      qual: nil,
      roles: ["authenticated"],
      with_check:
        "((realtime.topic() = ('user:'::text || auth.uid())) AND (extension = ANY (ARRAY['broadcast'::text, 'presence'::text])))"
    },
    %{
      cmd: "a",
      name: "users send on own channel (initplan)",
      permissive: true,
      qual: nil,
      roles: ["authenticated"],
      with_check:
        "((realtime.topic() = ('user:'::text || ( SELECT auth.uid() AS uid))) AND (extension = ANY (ARRAY['broadcast'::text, 'presence'::text])))"
    }
  ],
  server_version_num: 150_019
}
