defmodule RealtimeWeb.UserSocket do
  # Raise Phoenix's built-in per-transport channel limit above its default of 100. Realtime
  # enforces its own per-tenant `max_channels_per_client` limit (default 100) in RealtimeChannel
  # with a dedicated error message, so we just bump to a very large number.
  use Phoenix.Socket, max_channels_per_transport: 99_999
  use Realtime.Logs

  alias Realtime.Api.Tenant
  alias Realtime.Database
  alias Realtime.Tenants

  alias RealtimeWeb.TenantRateLimiters
  alias RealtimeWeb.ChannelsAuthorization
  alias RealtimeWeb.RealtimeChannel
  alias RealtimeWeb.RealtimeChannel.Logging
  alias RealtimeWeb.RealtimeChannel.MessageDispatcher

  ## Channels
  channel "realtime:*", RealtimeChannel

  @default_log_level :error

  ## Transport callbacks
  #
  # Wrap the callbacks generated by `use Phoenix.Socket` and delegate to them with `super`.

  defoverridable init: 1, handle_in: 2, handle_info: 2

  @impl Phoenix.Socket.Transport
  def init(state) do
    Process.flag(:max_heap_size, :persistent_term.get({__MODULE__, :websocket_max_heap_size}))
    Process.send_after(self(), {:measure_traffic, 0, 0}, measure_traffic_interval_in_ms())

    {:ok, {state, socket}} = super(state)
    {:ok, {state, start_no_channels_timer(socket, no_channel_timeout_in_ms())}}
  end

  @impl Phoenix.Socket.Transport
  def handle_in(message, {_state, socket} = full_state) do
    case super(message, full_state) do
      # A rejected duplicate join drops the existing channel without going through handle_info/2
      {:reply, :error, reply, {%{channels: channels} = state, socket}} when channels == %{} ->
        {:reply, :error, reply, {state, ensure_no_channels_timer(socket, no_channel_timeout_in_ms())}}

      result ->
        result
    end
  rescue
    e in Phoenix.Socket.InvalidMessageError ->
      Logging.log_error(socket, "MalformedWebSocketMessage", e.message)
      {:ok, full_state}

    e in Jason.DecodeError ->
      Logging.log_error(socket, "MalformedWebSocketMessage", Jason.DecodeError.message(e))
      {:ok, full_state}

    e ->
      Logging.log_error(socket, "UnknownErrorOnWebSocketMessage", Exception.message(e))
      {:ok, full_state}
  end

  @impl Phoenix.Socket.Transport
  def handle_info({:measure_traffic, previous_recv, previous_send}, {_, socket} = state) do
    %{latest_recv: latest_recv, latest_send: latest_send} =
      collect_traffic_telemetry(
        socket.transport_pid,
        Map.get(socket.assigns, :tenant),
        previous_recv,
        previous_send
      )

    Process.send_after(self(), {:measure_traffic, latest_recv, latest_send}, measure_traffic_interval_in_ms())
    {:ok, state}
  end

  def handle_info({:timeout, ref, :no_channels}, {state, %{private: %{no_channels_timer: ref}} = socket} = full_state) do
    if state.channels == %{} do
      Logger.info("Disconnecting socket with no channels open")
      # 1001 ("Going Away") keeps the previous behaviour of clients reconnecting
      {:stop, {:shutdown, :no_channels}, {1001, "No channels joined"}, full_state}
    else
      {:ok, {state, clear_no_channels_timer(socket)}}
    end
  end

  # The only messages that remove channels: a channel exiting or a channel closing
  def handle_info({:DOWN, _, _, _, _} = message, {%{channels: channels}, _} = state) when channels != %{} do
    message |> super(state) |> restart_if_no_channels(no_channel_timeout_in_ms())
  end

  def handle_info({:socket_close, _, _} = message, {%{channels: channels}, _} = state) when channels != %{} do
    message |> super(state) |> restart_if_no_channels(no_channel_timeout_in_ms())
  end

  def handle_info(message, state), do: super(message, state)

  @impl true
  def connect(params, socket, opts) do
    %{uri: %{host: host}, x_headers: headers} = opts

    {:ok, external_id} = Database.get_external_id(host)
    token = access_token(params, headers)
    log_level = log_level(params)

    Logger.metadata(external_id: external_id, project: external_id)
    Logger.put_process_level(self(), log_level)

    socket =
      socket
      |> assign(:tenant, external_id)
      |> assign(:log_level, log_level)
      |> assign(:access_token, token)

    with {:ok,
          %Tenant{
            jwt_secret: jwt_secret,
            jwt_jwks: jwt_jwks,
            suspend: false
          } = tenant} <- Tenants.Cache.fetch_tenant_by_external_id(external_id),
         {:ok, token} <- validate_token(token),
         jwt_secret_dec <- Tenant.decrypt_jwt_secret(jwt_secret),
         {:ok, claims} <- ChannelsAuthorization.authorize_conn(token, jwt_secret_dec, jwt_jwks),
         :ok <- TenantRateLimiters.check_tenant(tenant) do
      assigns = %RealtimeChannel.Assigns{
        claims: claims,
        jwt_secret: jwt_secret,
        jwt_jwks: jwt_jwks,
        tenant: external_id,
        log_level: log_level,
        tenant_token: token,
        headers: opts.x_headers
      }

      assigns = Map.from_struct(assigns)

      {:ok, assign(socket, assigns)}
    else
      {:error, :tenant_not_found} ->
        log_error("TenantNotFound", "Tenant not found: #{external_id}")
        connect_error(:tenant_not_found)

      {:ok, %Tenant{suspend: true}} ->
        Logging.log_error(socket, "RealtimeDisabledForTenant", "Realtime disabled for this tenant")
        connect_error(:tenant_suspended)

      {:error, :missing_api_key} ->
        log_error("MissingAPIKey", "API key is missing or not a valid string")
        connect_error(:missing_api_key)

      {:error, :expired_token, msg} ->
        Logging.maybe_log_warning(socket, "InvalidJWTToken", msg)
        connect_error(:expired_token)

      {:error, :missing_claims} ->
        msg = "Fields `role` and `exp` are required in JWT"
        Logging.maybe_log_warning(socket, "InvalidJWTToken", msg)
        connect_error(:missing_claims)

      {:error, :token_malformed} ->
        log_error("MalformedJWT", "The token provided is not a valid JWT")
        connect_error(:token_malformed)

      {:error, :too_many_connections} ->
        msg = "Too many connected users"
        Logging.log_error(socket, "ConnectionRateLimitReached", msg)
        connect_error(:too_many_connections)

      {:error, :too_many_joins} ->
        msg = "Too many joins per second"
        Logging.log_error(socket, "JoinsRateLimitReached", msg)
        connect_error(:too_many_joins)

      error ->
        log_error("ErrorConnectingToWebsocket", error)
        connect_error(error)
    end
  end

  @doc """
  Maps `connect/3` error reasons to proper HTTP responses for the WebSocket handshake.

  Configured as the `:error_handler` for the socket in `RealtimeWeb.Endpoint`.
  """
  @spec handle_error(Plug.Conn.t(), term()) :: Plug.Conn.t()
  def handle_error(conn, reason) do
    {status, message} = error_response(reason)

    conn
    |> Plug.Conn.put_resp_content_type("application/json")
    |> Plug.Conn.send_resp(status, Jason.encode!(%{error: message}))
  end

  defp error_response({:error, reason}), do: error_response(reason)
  defp error_response(:missing_api_key), do: {401, "API key is missing"}
  defp error_response(:expired_token), do: {401, "Token has expired"}
  defp error_response(:missing_claims), do: {401, "Fields `role` and `exp` are required in JWT"}
  defp error_response(:token_malformed), do: {401, "The token provided is not a valid JWT"}
  defp error_response(:invalid_token), do: {401, "The token provided is not a valid JWT"}
  defp error_response(:signature_error), do: {401, "Failed to validate JWT signature"}

  defp error_response(:error_generating_signer),
    do: {401, "Failed to generate JWT signer, check your JWT secret or JWKS configuration"}

  defp error_response({:error_generating_signer, kid}) do
    {401, "Failed to generate JWT signer for key ID (kid) #{inspect(kid)}, check your JWT secret or JWKS configuration"}
  end

  defp error_response(:tenant_suspended), do: {403, "Realtime was disabled for this tenant"}

  defp error_response(:tenant_not_found), do: {404, "Tenant not found"}

  defp error_response(:too_many_connections), do: {429, "Too many connected users"}
  defp error_response(:too_many_joins), do: {429, "Too many joins per second"}

  defp error_response(_reason), do: {500, "Error connecting to Realtime"}

  defp access_token(params, headers) do
    case :proplists.lookup("x-api-key", headers) do
      :none -> Map.get(params, "apikey")
      {"x-api-key", token} -> token
    end
  end

  defp log_level(params) do
    case Map.get(params, "log_level") do
      level when level in ["info", "warning", "error"] -> String.to_existing_atom(level)
      _ -> @default_log_level
    end
  end

  defp validate_token(token) when is_binary(token), do: {:ok, token}
  defp validate_token(_), do: {:error, :missing_api_key}

  defp connect_error(reason) do
    Process.sleep(connect_error_backoff_ms())
    {:error, reason}
  end

  defp connect_error_backoff_ms, do: :persistent_term.get({__MODULE__, :connect_error_backoff_ms})

  defp measure_traffic_interval_in_ms, do: :persistent_term.get({__MODULE__, :measure_traffic_interval_in_ms})
  defp no_channel_timeout_in_ms, do: :persistent_term.get({__MODULE__, :no_channel_timeout_in_ms})

  # The timer runs from the moment a socket is left without channels.
  defp start_no_channels_timer(socket, timeout) do
    if ref = socket.private[:no_channels_timer], do: :erlang.cancel_timer(ref, async: true, info: false)
    put_no_channels_timer(socket, :erlang.start_timer(timeout, self(), :no_channels))
  end

  defp ensure_no_channels_timer(%{private: %{no_channels_timer: ref}} = socket, _) when is_reference(ref), do: socket
  defp ensure_no_channels_timer(socket, timeout), do: start_no_channels_timer(socket, timeout)

  defp clear_no_channels_timer(socket), do: put_no_channels_timer(socket, nil)

  defp restart_if_no_channels({:ok, state}, timeout), do: {:ok, restart(state, timeout)}
  defp restart_if_no_channels({:push, msg, state}, timeout), do: {:push, msg, restart(state, timeout)}
  defp restart_if_no_channels(result, _timeout), do: result

  defp restart({%{channels: channels} = state, socket}, timeout) when channels == %{},
    do: {state, start_no_channels_timer(socket, timeout)}

  defp restart(state, _timeout), do: state

  defp put_no_channels_timer(socket, ref),
    do: %{socket | private: Map.put(socket.private, :no_channels_timer, ref)}

  defp collect_traffic_telemetry(nil, _tenant_external_id, previous_recv, previous_send),
    do: %{latest_recv: previous_recv, latest_send: previous_send}

  defp collect_traffic_telemetry(transport_pid, tenant_external_id, previous_recv, previous_send) do
    %{send_oct: latest_send, recv_oct: latest_recv} =
      transport_pid
      |> Process.info(:links)
      |> then(fn {:links, links} -> links end)
      |> Enum.filter(&is_port/1)
      |> Enum.reduce(%{send_oct: 0, recv_oct: 0}, fn link, acc ->
        case :inet.getstat(link, [:send_oct, :recv_oct]) do
          {:ok, stats} ->
            send_oct = Keyword.get(stats, :send_oct, 0)
            recv_oct = Keyword.get(stats, :recv_oct, 0)
            %{send_oct: acc.send_oct + send_oct, recv_oct: acc.recv_oct + recv_oct}

          {:error, _} ->
            acc
        end
      end)

    send_delta = max(0, latest_send - previous_send)
    recv_delta = max(0, latest_recv - previous_recv)

    :telemetry.execute([:realtime, :channel, :output_bytes], %{size: send_delta}, %{tenant: tenant_external_id})
    :telemetry.execute([:realtime, :channel, :input_bytes], %{size: recv_delta}, %{tenant: tenant_external_id})

    %{latest_recv: latest_recv, latest_send: latest_send}
  end

  @impl true
  def id(%{assigns: %{tenant: tenant}}), do: subscribers_id(tenant)

  @spec subscribers_id(String.t()) :: String.t()
  def subscribers_id(tenant), do: "user_socket:" <> tenant

  @spec disconnect(binary()) :: :ok
  def disconnect(tenant_external_id) do
    Logger.warning("Disconnecting all sockets for tenant #{tenant_external_id}",
      external_id: tenant_external_id,
      project: tenant_external_id
    )

    disconnect_msg = %Phoenix.Socket.Broadcast{
      event: "system",
      payload: %{extension: "system", status: "ok", message: "Server requested disconnect"}
    }

    Phoenix.PubSub.broadcast!(
      Realtime.PubSub,
      "realtime:operations:" <> tenant_external_id,
      disconnect_msg,
      MessageDispatcher
    )

    Phoenix.PubSub.broadcast(Realtime.PubSub, subscribers_id(tenant_external_id), :socket_drain)
    :ok
  end
end
