-- Realtime Testing Suite Setup

drop publication if exists supabase_realtime_test;
create publication supabase_realtime_test for all tables;

drop schema if exists realtime cascade;
create schema realtime;

create table if not exists public.todos (
  id bigint generated by default as identity primary key,
  details text,
  user_id bigint not null
);

grant all on all tables in schema public to authenticated;
