defmodule Realtime.Tenants.SqlLogexFixturesTest do
  # sql_logex parses the text Postgres returns from pg_get_expr, so the parser is written against
  # captured output. This test captures it again and fails when the running Postgres reports anything
  # else than the checked-in fixture of its major version, that is how drift between versions shows up.
  #
  #   SQL_LOGEX_WRITE_FIXTURES=1 mix test test/realtime/tenants/sql_logex_fixtures_test.exs
  #   POSTGRES_IMAGE=supabase/postgres:15.19.0.004 SQL_LOGEX_WRITE_FIXTURES=1 mix test test/realtime/tenants/sql_logex_fixtures_test.exs
  use Realtime.DataCase, async: true

  alias Realtime.Database

  @fixtures_dir Path.expand("../../../sql_logex/test/fixtures", __DIR__)

  @policies_query """
  select polname, polcmd::text, polpermissive,
         array(select case when r = 0 then 'public' else r::regrole::text end from unnest(polroles) r),
         pg_get_expr(polqual, polrelid), pg_get_expr(polwithcheck, polrelid)
  from pg_policy where polrelid = 'realtime.messages'::regclass order by polname
  """

  @functions_query """
  select n.nspname, p.proname, l.lanname, p.provolatile::text, p.prosecdef, p.proconfig,
         p.prorettype::regtype::text, p.prosrc
  from pg_proc p
  join pg_namespace n on n.oid = p.pronamespace
  join pg_language l on l.oid = p.prolang
  where p.pronargs = 0 and (n.nspname, p.proname) in (('auth', 'uid'), ('auth', 'jwt'), ('auth', 'role'), ('realtime', 'topic'))
  order by n.nspname, p.proname
  """

  @database_query """
  select current_setting('server_version_num'), datcollate, datctype, datlocprovider::text
  from pg_database where datname = current_database()
  """

  setup do
    tenant = TestTenantDb.checkout_tenant(run_migrations: true)
    {:ok, db_conn} = Database.connect(tenant, "realtime_test", :stop)
    %{db_conn: db_conn}
  end

  test "policies and functions are reported as in the fixture of this Postgres version", %{db_conn: db_conn} do
    {:error, actual} =
      Postgrex.transaction(db_conn, fn conn ->
        # As a customer would create them
        create_policies!(conn)

        # Pinned so function and operator names are deparsed schema-qualified
        Postgrex.query!(conn, "SET LOCAL search_path = ''", [])
        Postgrex.rollback(conn, capture(conn))
      end)

    path = Path.join([@fixtures_dir, "pg#{div(actual.server_version_num, 10_000)}", "catalog.exs"])

    if System.get_env("SQL_LOGEX_WRITE_FIXTURES") == "1" do
      write_fixture!(path, actual)
    else
      assert_fixture(path, actual)
    end
  end

  defp create_policies!(conn) do
    # Creates test_log_error(), needed by the broken_* policies
    Generators.create_rls_policies(conn, [], SqlLogexPolicies.generator_policies().params)
    Postgrex.query!(conn, SqlLogexPolicies.auth_jwt_statement(), [])

    statements =
      SqlLogexPolicies.user_channel_policies() ++
        SqlLogexPolicies.grammar_policies() ++ SqlLogexPolicies.generator_statements()

    Enum.each(statements, &Postgrex.query!(conn, &1, []))
  end

  defp capture(conn) do
    %{rows: [[version_num, collate, ctype, locprovider]]} = Postgrex.query!(conn, @database_query, [])
    %{rows: policies} = Postgrex.query!(conn, @policies_query, [])
    %{rows: functions} = Postgrex.query!(conn, @functions_query, [])

    %{
      server_version_num: String.to_integer(version_num),
      database: %{collate: collate, ctype: ctype, locale_provider: locprovider},
      policies:
        for [name, cmd, permissive, roles, qual, with_check] <- policies do
          %{name: name, cmd: cmd, permissive: permissive, roles: roles, qual: qual, with_check: with_check}
        end,
      functions:
        for [schema, name, language, volatility, security_definer, config, return_type, source] <- functions do
          %{
            schema: schema,
            name: name,
            language: language,
            volatility: volatility,
            security_definer: security_definer,
            config: config,
            return_type: return_type,
            source: source
          }
        end
    }
  end

  defp write_fixture!(path, actual) do
    formatted =
      actual
      # Sorted, or the key order changes from one run to the next and so does the diff
      |> inspect(pretty: true, limit: :infinity, printable_limit: :infinity, custom_options: [sort_maps: true])
      |> Code.format_string!(line_length: 120)

    File.mkdir_p!(Path.dirname(path))
    File.write!(path, [header(), formatted, "\n"])
  end

  defp header do
    """
    # What Postgres reports for the policies of test/support/sql_logex_policies.ex and for the functions
    # they call. Generated by test/realtime/tenants/sql_logex_fixtures_test.exs, do not edit by hand.
    #
    # To regenerate, run this against a Postgres of this major version (POSTGRES_IMAGE selects it):
    #
    #   SQL_LOGEX_WRITE_FIXTURES=1 mix test test/realtime/tenants/sql_logex_fixtures_test.exs
    #
    """
  end

  defp assert_fixture(path, actual) do
    unless File.exists?(path) do
      flunk("""
      No fixture for Postgres #{actual.server_version_num} at #{Path.relative_to_cwd(path)}.
      Generate it with: SQL_LOGEX_WRITE_FIXTURES=1 mix test test/realtime/tenants/sql_logex_fixtures_test.exs
      """)
    end

    {expected, _binding} = Code.eval_file(path)

    # Section by section, so a failure shows only what differs. The fixture is chosen by major
    # version, so a minor image bump alone doesn't fail this.
    assert Map.keys(actual) == Map.keys(expected)
    assert actual.database == expected.database
    assert actual.functions == expected.functions
    assert actual.policies == expected.policies
  end
end
