name: Docker Build

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  docker_x86_build:
    runs-on: blacksmith-4vcpu-ubuntu-2404
    timeout-minutes: 120
    env:
      arch: amd64
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Setup Blacksmith Builder
        uses: useblacksmith/setup-docker-builder@ef12d5b165b596e3aa44ea8198d8fde563eab402 # v1.4.0

      - uses: useblacksmith/build-push-action@30c71162f16ea2c27c3e21523255d209b8b538c1 # v2
        with:
          context: .
          push: false
          platforms: linux/${{ env.arch }}

  docker_arm_build:
    runs-on: blacksmith-4vcpu-ubuntu-2404-arm
    timeout-minutes: 120
    env:
      arch: arm64
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Setup Blacksmith Builder
        uses: useblacksmith/setup-docker-builder@ef12d5b165b596e3aa44ea8198d8fde563eab402 # v1.4.0

      - uses: useblacksmith/build-push-action@30c71162f16ea2c27c3e21523255d209b8b538c1 # v2
        with:
          context: .
          push: false
          platforms: linux/${{ env.arch }}
