name: Manual Build Production
on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch to run the workflow"
        required: true
      docker_tag:
        description: "Tag to be used by the docker image on push"
        required: true
jobs:
  docker_x86_release:
    runs-on: blacksmith-4vcpu-ubuntu-2404
    timeout-minutes: 120
    env:
      arch: amd64
    outputs:
      image_digest: ${{ steps.build.outputs.digest }}
    steps:
      - id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            supabase/realtime
          tags: |
            type=raw,value=v${{ github.event.inputs.docker_tag }}_${{ env.arch }}

      - name: Setup Blacksmith Builder
        uses: useblacksmith/setup-docker-builder@v1

      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - id: build
        uses: useblacksmith/build-push-action@v2
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          platforms: linux/${{ env.arch }}

  docker_arm_release:
    runs-on: arm-runner
    timeout-minutes: 120
    env:
      arch: arm64
    outputs:
      image_digest: ${{ steps.build.outputs.digest }}
    steps:
      - uses: actions/checkout@v3

      - id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            supabase/realtime
          tags: |
            type=raw,value=v${{ github.event.inputs.docker_tag }}_${{ env.arch }}

      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Setup Blacksmith Builder
        uses: useblacksmith/setup-docker-builder@v1

      - id: build
        uses: useblacksmith/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          platforms: linux/${{ env.arch }}
          no-cache: true

  merge_manifest:
    needs: [docker_x86_release, docker_arm_release]
    runs-on: blacksmith-4vcpu-ubuntu-2404
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - name: Setup Blacksmith Builder
        uses: useblacksmith/setup-docker-builder@v1

      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Merge multi-arch manifests for custom output
        run: |
          docker buildx imagetools create -t supabase/realtime:v${{ github.event.inputs.docker_tag }} \
          supabase/realtime@${{ needs.docker_x86_release.outputs.image_digest }} \
          supabase/realtime@${{ needs.docker_arm_release.outputs.image_digest }}

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.PROD_AWS_ROLE }}
          aws-region: us-east-1

      - name: Login to ECR
        uses: docker/login-action@v2
        with:
          registry: public.ecr.aws

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Mirror to ECR
        uses: akhilerm/tag-push-action@v2.0.0
        with:
          src: docker.io/supabase/realtime:v${{ github.event.inputs.docker_tag }}
          dst: |
            public.ecr.aws/supabase/realtime:v${{ github.event.inputs.docker_tag }}
            ghcr.io/supabase/realtime:v${{ github.event.inputs.docker_tag }}

