name: Mirror to ECR

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Image tag"
        required: true
        type: string

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: docker/login-action@v2
        with:
          registry: public.ecr.aws
          username: ${{ secrets.PROD_ACCESS_KEY_ID }}
          password: ${{ secrets.PROD_SECRET_ACCESS_KEY }}
      - uses: akhilerm/tag-push-action@v2.0.0
        with:
          src: docker.io/supabase/realtime:${{ inputs.version }}
          dst: public.ecr.aws/t3w2s2c9/realtime:${{ inputs.version }}
